net: dwmac-socfpga: add explicit dependency on Lynx PCS
DMWAC SocFPGA is missing a dependency on Lynx PCS since it now uses Lynx
PCS as à reg-mapped mdio PCS

/workspace/new_build/out/output-diamond/host/bin/arm-linux-ld: drivers/net/ethernet/altera/altera_tse_main.o: in function `altera_tse_probe':
altera_tse_main.c:(.text+0xeb4): undefined reference to `lynx_pcs_create'
/workspace/new_build/out/output-diamond/host/bin/arm-linux-ld: drivers/net/ethernet/stmicro/stmmac/dwmac-socfpga.o: in function `socfpga_dwmac_probe':
dwmac-socfpga.c:(.text+0x820): undefined reference to `lynx_pcs_create'

Signed-off-by: Alexis Lothoré <alexis.lothore@bootlin.com>