net: mdio-regmap: add missing metadata to build as module
mdio-regamp is missing MODULE_DESCRIPTION, MODULE_AUTHOR and
MODULE_LICENCE:

ERROR: modpost: missing MODULE_LICENSE() in drivers/net/mdio/mdio-regmap.o
make[3]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
make[2]: *** [Makefile:1964: modpost] Error 2
make[2]: Leaving directory '/workspace/new_build/out/output-diamond/build/linux-custom'
make[1]: *** [package/pkg-generic.mk:293: /workspace/new_build/out/output-diamond/build/linux-custom/.stamp_built] Error 2
make[1]: Leaving directory '/workspace/new_build/build/buildroot'
make: *** [/workspace/new_build/build/matchbox/targets.mk:35: diamond] Error 2

Signed-off-by: Alexis Lothoré <alexis.lothore@bootlin.com>